version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 50
    groups:
      github:
        patterns:
          - "actions/*"
  - package-ecosystem: "gradle"
    directories:
      - "/"
      - "/examples/ExampleApp"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 50
