#!/bin/bash
set -euo pipefail

# Create a PR that bumps the snapshot version

next_version="${1:?Error: next_version required}"
run_id="${2:?Error: run_id required}"

.github/scripts/configure-git.sh

branch="sdk-version-update-${run_id}"
git checkout -b "$branch"

git add gradle.properties
git commit -m "CI/CD: set next version: ${next_version}-SNAPSHOT"
git push -f origin "$branch"

gh pr create \
    --base main \
    --head "$branch" \
    --title "CI/CD: set next version: ${next_version}-SNAPSHOT" \
    --body "This is an autogenerated PR, created by the bump-snapshot-version.yml workflow"
