include(
    ":embrace-android-api",
    ":embrace-android-sdk",
    ":embrace-android-okhttp3",
    ":embrace-android-fcm",
    ":embrace-android-compose",
    ":embrace-lint",
    ":embrace-test-common"
)
