package io.embrace.android.exampleapp.paradigms.data

import android.content.Context
import kotlinx.serialization.json.Json

/**
 * On-demand sample data backed by JSON files in `assets/sample/`.
 *
 * Designed for scroll-perf testing: each list is loaded + deserialized lazily on first access,
 * so the parsing cost lands on first paradigm-screen open rather than at cold start. The
 * underlying JSON is generated by `tools/gen_sample.py` (run from a developer machine);
 * regenerate to grow or shrink dataset sizes.
 */
object SampleData {

    @PublishedApi
    internal var appContextOrNull: Context? = null

    @PublishedApi
    internal val json: Json = Json {
        ignoreUnknownKeys = true
        encodeDefaults = false
        classDiscriminator = "type"
        explicitNulls = false
    }

    fun init(context: Context) {
        if (appContextOrNull == null) {
            appContextOrNull = context.applicationContext
        }
    }

    val postAuthors: List<PostAuthor> by lazy { readList("sample/authors.json") }
    val posts: List<Post> by lazy { readList("sample/posts.json") }
    val newsSections: List<NewsSection> by lazy { readList("sample/sections.json") }
    val articles: List<Article> by lazy { readList("sample/articles.json") }
    val productCategories: List<ProductCategory> by lazy { readList("sample/categories.json") }
    val products: List<Product> by lazy { readList("sample/products.json") }

    fun post(id: String): Post? = posts.firstOrNull { it.id == id }
    fun author(handle: String): PostAuthor? = postAuthors.firstOrNull { it.handle == handle }
    fun article(id: String): Article? = articles.firstOrNull { it.id == id }
    fun section(id: String): NewsSection? = newsSections.firstOrNull { it.id == id }
    fun product(id: String): Product? = products.firstOrNull { it.id == id }
    fun category(id: String): ProductCategory? = productCategories.firstOrNull { it.id == id }
    fun articlesIn(sectionId: String): List<Article> = articles.filter { it.sectionId == sectionId }
    fun productsIn(categoryId: String): List<Product> = products.filter { it.categoryId == categoryId }

    @PublishedApi
    internal inline fun <reified T> readList(path: String): List<T> {
        val context = checkNotNull(appContextOrNull) {
            "SampleData.init(context) must be called before reading $path"
        }
        val text = context.assets.open(path).bufferedReader().use { it.readText() }
        return json.decodeFromString(text)
    }
}
