package io.embrace.android.embracesdk.internal.arch.schema

/**
 * Marks a value of a [SchemaType.State] as one generated by the SDK itself rather than observed from the app, e.g. a placeholder
 * for nothing having been observed yet. Such a value is recorded along with `emb.state.value_type=system` wherever the state
 * value appears, so that it can be told apart from an observed value that happens to have the same [toString] form.
 */
interface SystemStateValue
