package io.embrace.android.gradle.plugin.tasks

import java.io.File

/**
 * Writes a string resource file to the build directory, where it will be incorporated into the
 * APK's resources.
 */
class BuildResourceWriter {

    fun writeBuildInfoFile(
        dst: File,
        resValues: Map<String, String>
    ) {
        val parentFile = dst.parentFile
        if (parentFile != null) {
            parentFile.mkdirs()
            val buildInfoXmlContent = createStringsXmlFile(resValues)
            dst.writeText(buildInfoXmlContent)
        }
    }

    private fun createStringsXmlFile(
        resValues: Map<String, String>
    ): String {
        val sb = StringBuilder(256)
        sb.append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n")
        sb.append("<resources xmlns:tools=\"http://schemas.android.com/tools\">\n")
        sb.append("<!--This file is automatically generated by Embrace-->\n")

        for ((key, value) in resValues) {
            sb.append("    <string name=\"").append(key).append("\"")
            sb.append(">").append(value).append("</string>\n")
        }
        sb.append("</resources>\n")
        return sb.toString()
    }
}
