package io.embrace.android.embracesdk.instrumentation.leaks

import android.view.View
import androidx.fragment.app.Fragment
import java.lang.ref.WeakReference
import java.util.WeakHashMap

/**
 * Lightweight wrapper around a `WeakHashMap` so that we can track the `View` objects generated by `Fragment`s weakly, safely and without
 * relying on `Fragment.getView()` (which may be `null`ed before we can mark their lifecycle as complete).
 */
@JvmInline
internal value class FragmentViewMap private constructor(
    private val views: WeakHashMap<Fragment, WeakReference<View>>,
) {
    constructor() : this(WeakHashMap())

    fun opened(fragment: Fragment, view: View) {
        views[fragment] = WeakReference(view)
    }

    /**
     * Returns the view seen at [opened] for [fragment], or null if none was recorded or it has already been collected.
     */
    fun closed(fragment: Fragment): View? {
        return views.remove(fragment)?.get()
    }
}
