# yaml-language-server: $schema=../../../buildSrc/src/main/resources/config.schema.json
PersistenceConfig:
  multi_file_persistence_enabled:
    property: multiFileEnabled
    default: false
    local:
      type: Boolean
      sdk: enabledFeatures.isMultiFilePersistenceEnabled()
    remote:
      type: Pct
      sdk: pctMultiFilePersistenceEnabled
