package io.embrace.android.embracesdk.internal.api

import android.app.Activity
import io.embrace.android.embracesdk.annotation.InternalApi
import io.embrace.android.embracesdk.spans.EmbraceSpanEvent
import io.embrace.android.embracesdk.spans.ErrorCode

/**
 * API to control and customize Embrace instrumentation
 */
@InternalApi
public interface InstrumentationApi {

    /**
     * Notify the Embrace UI Load instrumentation that the given [Activity] instance has fully loaded, so its associated
     * trace can be stopped
     */
    public fun activityLoaded(activity: Activity)

    /**
     * Return the timestamp of the SDK clock. This value should be used when creating spans with specific start and
     * end times so that
     */
    public fun getSdkCurrentTimeMs(): Long

    /**
     * Add an attribute to the trace generated by the loading of the given [Activity]
     */
    public fun addLoadTraceAttribute(activity: Activity, key: String, value: String)

    /**
     * Add a successfully completed child span to the trace generated by the loading of the given [Activity]
     */
    public fun addLoadTraceChildSpan(
        activity: Activity,
        name: String,
        startTimeMs: Long,
        endTimeMs: Long,
    ): Unit = addLoadTraceChildSpan(
        activity = activity,
        name = name,
        startTimeMs = startTimeMs,
        endTimeMs = endTimeMs,
        attributes = emptyMap(),
        events = emptyList(),
        errorCode = null,
    )

    /**
     * Add a completed child span to the trace generated by the loading of the given [Activity] with the given
     * attributes and span events. Specify an [ErrorCode] if the span didn't complete successfully.
     */
    public fun addLoadTraceChildSpan(
        activity: Activity,
        name: String,
        startTimeMs: Long,
        endTimeMs: Long,
        attributes: Map<String, String>,
        events: List<EmbraceSpanEvent>,
        errorCode: ErrorCode?,
    )

    /**
     * Add an attribute to the app startup trace
     */
    public fun addStartupTraceAttribute(key: String, value: String)

    /**
     * Add a successfully completed child span to the app startup trace
     */
    public fun addStartupTraceChildSpan(
        name: String,
        startTimeMs: Long,
        endTimeMs: Long,
    ): Unit = addStartupTraceChildSpan(
        name = name,
        startTimeMs = startTimeMs,
        endTimeMs = endTimeMs,
        attributes = emptyMap(),
        events = emptyList(),
        errorCode = null,
    )

    /**
     * Add a completed child span to the app startup trace with the given  attributes and span events.
     * Specify an [ErrorCode] if the span didn't complete successfully.
     */
    public fun addStartupTraceChildSpan(
        name: String,
        startTimeMs: Long,
        endTimeMs: Long,
        attributes: Map<String, String>,
        events: List<EmbraceSpanEvent>,
        errorCode: ErrorCode?,
    )
}
