/**
 * Embrace Envelope API
 *
 * The payloads we send to the Embrace backend do not map directly to an OTLP spec or even a specific concept.
 * Rather, they will contain objects that map to OTel concepts like resources, spans, and logs,
 * represented by a custom JSON serialization format that mirrors, more or less, the official Protobuf definitions.
 * But the structure within which these wrapper objects live will be Embrace-specific
 * and be tailored to our existing lifecycle.
 * In general, all payloads will share a common envelope that contains shared attributes that
 * we don’t want to duplicate -
 * largely what was included in appInfo, deviceInfo, and userInfo. It will also have a `data` object where custom,
 * payload-specific data can be stored, which is unique for each payload type
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@embrace.io
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package io.embrace.android.embracesdk.internal.payload

import io.embrace.android.embracesdk.internal.serialization.EnvelopeResourceSerializer
import kotlinx.serialization.Serializable

/**
 * Immutable attributes about the app, device, and Embrace SDK internal state for duration of an app launch.
 * Contains what previously was in AppInfo and DeviceInfo
 *
 * @param appVersion The app's publicly displayed version name. Previous name: a.v
 * @param appFramework The frameworks in use by the app. 1=Native, 2=React Native, 3=Unity. Previous name: a.f
 * @param buildId A unique ID for the build that is generated at build time. Previous name: a.bi
 * @param appEcosystemId Unique identifier for the app in its ecosystem.
 * In Apple, this is the Bundle ID (e.g. com.io.embrace).
 * In Android, this is the app's package name (e.g. io.embrace.testapp). Previous name: a.bid
 * @param buildType (Android) - the buildType name. Previous name: a.bt
 * @param buildFlavor (Android) - the flavor name. If productFlavors are not used this will be null. Previous name: a.fl
 * @param environment The name of the environment, i.e. dev or prod. Previous name: a.e
 * @param bundleVersion The app bundle version (on Android this is versionCode). Previous name: a.bv
 * @param sdkVersion The version number of the Embrace SDK. Previous name: a.sdk
 * @param sdkSimpleVersion The simple version number of the Embrace SDK. Previous name: a.sdc
 * @param reactNativeBundleId (React Native) the MD5 hash of the React Native bundle file. Previous name: a.rn
 * @param reactNativeVersion (React Native) the React Native version number. Previous name: a.rnv
 * @param javascriptPatchNumber (React Native) the JavaScript patch number. Previous name: a.jsp
 * @param hostedPlatformVersion The version of the hosted platform engine, i.e.
 * Unity/React Native/Flutter. Previous name: a.unv
 * @param hostedSdkVersion The version of the hosted SDK used. Previous name: a.usv
 * @param unityBuildId (Unity) the Unity build ID number. Previous name: a.ubg
 * @param deviceManufacturer The device manufacturer. Previous name: d.dm
 * @param deviceModel The device model. Previous name: d.do
 * @param deviceArchitecture The CPU architecture used by the device. Previous name: d.da
 * @param jailbroken Whether the device is rooted/jailbroken or not. Previous name: d.jb
 * @param diskTotalCapacity The total capacity of internal storage for the whole device. Previous name: d.ms
 * @param osType A hardcoded string representing the operating system in use. Previous name: d.os
 * @param osVersion The human readable OS version string. Previous name: d.ov
 * @param osCode (Android) The OS version code. Previous name: d.oc
 * @param screenResolution The screen resolution. Previous name: d.sr
 * @param numCores (Android) The number of CPU cores the device has. Previous name: d.nc
 */

@Serializable(with = EnvelopeResourceSerializer::class)
data class EnvelopeResource(

    /**** WARNING: when altering fields, please keep JSON keys in sync with
     * [io.embrace.android.embracesdk.internal.serialization.EnvelopeResourceSerializer]. ****/

    /* The app's publicly displayed version name. Previous name: a.v */
    val appVersion: String? = null,

    /* The frameworks in use by the app. 1=Native, 2=React Native, 3=Unity, 4=Flutter. Previous name: a.f */
    val appFramework: AppFramework? = null,

    /* A unique ID for the build that is generated at build time. Previous name: a.bi */
    val buildId: String? = null,

    /* Unique identifier for the app in its ecosystem. In Apple, this is the Bundle ID (e.g. com.io.embrace).
    In Android, this is the app's package name (e.g. io.embrace.testapp). Previous name: a.bid */
    val appEcosystemId: String? = null,

    /* (Android) - the buildType name. Previous name: a.bt */
    val buildType: String? = null,

    /* (Android) - the flavor name. If productFlavors are not used this will be null. Previous name: a.fl */
    val buildFlavor: String? = null,

    /* The name of the environment, i.e. dev or prod. Previous name: a.e */
    val environment: String? = null,

    /* The app bundle version (on Android this is versionCode). Previous name: a.bv */
    val bundleVersion: String? = null,

    /* The version number of the Embrace SDK. Previous name: a.sdk */
    val sdkVersion: String? = null,

    /* The simple version number of the Embrace SDK. Previous name: a.sdc */
    val sdkSimpleVersion: Int? = null,

    /* (React Native) the MD5 hash of the React Native bundle file. Previous name: a.rn */
    val reactNativeBundleId: String? = null,

    /* (React Native) the React Native version number. Previous name: a.rnv */
    val reactNativeVersion: String? = null,

    /* (React Native) the JavaScript patch number. Previous name: a.jsp */
    val javascriptPatchNumber: String? = null,

    /* The version of the hosted platform engine, i.e. Unity/React Native/Flutter. Previous name: a.unv */
    val hostedPlatformVersion: String? = null,

    /* The version of the hosted SDK used. Previous name: a.usv */
    val hostedSdkVersion: String? = null,

    /* (Unity) the Unity build ID number. Previous name: a.ubg */
    val unityBuildId: String? = null,

    /* The device manufacturer. Previous name: d.dm */
    val deviceManufacturer: String? = null,

    /* The device model. Previous name: d.do */
    val deviceModel: String? = null,

    /* The CPU architecture used by the device. Previous name: d.da */
    val deviceArchitecture: String? = null,

    /* Whether the device is rooted/jailbroken or not. Previous name: d.jb */
    val jailbroken: Boolean? = null,

    /* The total capacity of internal storage for the whole device. Previous name: d.ms */
    val diskTotalCapacity: Long? = null,

    /* A hardcoded string representing type of operating system in use. */
    val osType: String? = null,

    /* The user understood name of the OS - hardcoded to "android" for this SDK. Previous name: d.os */
    val osName: String? = null,

    /* The human readable OS version string. Previous name: d.ov */
    val osVersion: String? = null,

    /* (Android) The OS version code. Previous name: d.oc */
    val osCode: String? = null,

    /* The screen resolution. Previous name: d.sr */
    val screenResolution: String? = null,

    /* (Android) The number of CPU cores the device has. Previous name: d.nc */
    val numCores: Int? = null,

    val extras: Map<String, String> = emptyMap(),
)
