package io.embrace.startup.analysis

import io.embrace.startup.core.json.PyJson
import io.embrace.startup.core.text.PyFormat
import io.embrace.startup.store.MaximsLedger
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonObject

/**
 * MAXIMS.md: the generated half of the maxims documentation, rendered from the maxim definitions in
 * [Maxims] and the ledger. The curated half (FINDINGS.md) is written by hand. Text matches the frozen
 * goldens line for line.
 */
object MaximsDoc {

    fun render(led: JsonObject, now: String): String {
        val b = ArrayList<String>()
        val runs = PyJson.str(led, "runs", "0")
        val maxims = PyJson.obj(led, "maxims") ?: JsonObject(emptyMap())
        b.preamble(led, now, runs)
        b.summaryTable(maxims)
        Maxims.ALL.forEach { m -> b.section(m, maxims[m.id] as? JsonObject, runs) }
        b.retired(maxims)
        b.candidates(PyJson.obj(led, "candidates") ?: JsonObject(emptyMap()))
        return b.joinToString("\n") + "\n"
    }

    private fun MutableList<String>.preamble(led: JsonObject, now: String, runs: String) {
        val updated = if (PyJson.truthy(led, "updated_at")) " (last updated ${PyJson.str(led, "updated_at", "")})" else ""
        add("# SDK startup maxims (bench)\n")
        add(
            "What we currently believe about Android SDK init from the benchmark fleet, and the evidence for it. " +
                "Generated by `maxims render` at $now from the maxim definitions in `startup-tools` " +
                "and a ledger of $runs runs" + updated +
                ". Do not edit by hand: change a maxim in code or score another campaign, then regenerate. " +
                "Conclusions that are not per-campaign checks are in [FINDINGS.md](FINDINGS.md). The production " +
                "counterpart with the same structure is `tool/sdk-startup/MAXIMS.md` in the go repository; a maxim " +
                "id that appears in both is the same claim tested on the fleet and on the bench.\n",
        )
        add(
            "**Scopes.** *Universal*: a claim about the SDK that should hold at the stated size on every device; " +
                "one device contradicting it counts against it. *Directional*: the direction holds everywhere but the " +
                "size is the device's, so a lift that points the right way but misses the floor is *undetected*, not " +
                "a contradiction. *Device-specific*: the sign itself is the device's, and the split by device is the " +
                "finding.\n",
        )
        add(
            "**Status.** *accepted*: every device that tested it holds it. *under review*: a device fails or is " +
                "mixed but most hold it. *refuted*: as many devices fail it as hold it. *untested*: no verdict yet. A " +
                "device *holds* a maxim when its confirmations outnumber contradictions two to one across every run, " +
                "*fails* when the reverse. A cell is one campaign: one device under one recipe and arm.\n",
        )
    }

    private fun MutableList<String>.summaryTable(maxims: JsonObject) {
        add("| maxim | scope | status | devices |")
        add("|---|---|---|---|")
        Maxims.ALL.forEach { m ->
            val t = maxims[m.id] as? JsonObject
            add("| ${m.id} | ${m.scope} | ${MaximsLedger.statusOf(m.scope, t)} | ${MaximsLedger.devicesLine(t)} |")
        }
        add("")
    }

    private fun MutableList<String>.section(m: Maxims.Maxim, t: JsonObject?, runs: String) {
        add("## ${m.id}\n")
        add("**${m.statement}**\n")
        add("- Scope: ${m.scope}. Status: **${MaximsLedger.statusOf(m.scope, t)}**.")
        add("- Why: ${m.why}")
        if (t.isNullOrEmpty()) {
            add("- Evidence: none yet.\n")
            return
        }
        var ev = "${text(t, "confirmed")} confirmed, ${text(t, "contradicted")} contradicted, ${text(t, "thin")} thin"
        if (PyJson.truthy(t, "undetected")) {
            ev += ", ${text(t, "undetected")} undetected"
        }
        add("- Evidence: $ev cells over $runs runs; ${MaximsLedger.devicesLine(t)}.")
        val contras = PyJson.arr(t, "contradictions")?.toList() ?: emptyList()
        if (contras.isNotEmpty()) {
            add("- Latest contradictions (cell, observed):")
            contras.takeLast(LATEST_CONTRADICTIONS).reversed().forEach { x ->
                add("  - ${text(x.jsonObject, "cell")}: ${text(x.jsonObject, "observed")}")
            }
        }
        add("")
    }

    /** Ledger records for maxim ids no longer defined in code. */
    private fun MutableList<String>.retired(maxims: JsonObject) {
        val current = Maxims.ALL.map { it.id }.toSet()
        val retired = maxims.keys.filter { it !in current }.sorted()
        if (retired.isEmpty()) {
            return
        }
        add("## Retired maxims\n")
        add(
            "Ledger records for maxims that are no longer defined in code - renamed, rewritten as a " +
                "different claim, or dropped. FINDINGS.md says why.\n",
        )
        add("| former id | statement as recorded | confirmed | contradicted | thin |")
        add("|---|---|---|---|---|")
        retired.forEach { k ->
            val t = maxims[k] as? JsonObject
            add("| $k | ${text(t, "statement")} | ${text(t, "confirmed")} | ${text(t, "contradicted")} | ${text(t, "thin")} |")
        }
        add("")
    }

    private fun MutableList<String>.candidates(candidates: JsonObject) {
        val cands = candidates.values
            .map { it.jsonObject }
            .sortedWith(compareBy({ -MaximsLedger.int(it, "cells") }, { PyJson.str(it, "label", "") }))
        if (cands.isEmpty()) {
            return
        }
        add("## Candidates\n")
        add(
            "Per-iteration factors whose top (or bottom) quartile was at least ${Maxims.CANDIDATE_LIFT}x as likely to be " +
                "slow in some campaign and that no maxim covers. One that keeps appearing is a maxim waiting to be " +
                "written - or a small band waiting to be disproved.\n",
        )
        add("| factor | cells | max lift | last seen |")
        add("|---|---|---|---|")
        cands.forEach { c ->
            val lift = PyJson.double(c, "max_lift") ?: 0.0
            add("| ${text(c, "label")} | ${text(c, "cells")} | ${PyFormat.fixed(lift, 2)}x | ${text(c, "last_seen")} |")
        }
        add("")
    }

    /** A field as Python's f-string would print it: the literal for numbers, the text for strings, "" if absent. */
    private fun text(obj: JsonObject?, key: String): String = PyJson.strOrNull(obj, key) ?: ""

    private const val LATEST_CONTRADICTIONS = 5
}
