name: Build Example App

on:
  push:
    branches: [ main ]
  pull_request:
  release:
    types: [ released ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-example-app:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@ac638b010cf58a27ee6c972d7336334ccaf61c96 # v4.4.1

      # Build the entire project, run the tests, and run all static analysis
      - name: Build example app
        working-directory: examples/ExampleApp
        run: ./gradlew bundleRelease
