name: Release beta version

env:
  MAVEN_QA_USER: github
  MAVEN_QA_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
  mavenSigningKeyId: ${{ secrets.MAVEN_ANDROID_SIGNING_KEY }}
  mavenSigningKeyRingFileEncoded: ${{ secrets.MAVEN_ANDROID_GPG_KEY }}
  mavenSigningKeyPassword: ${{ secrets.MAVEN_ANDROID_SIGNING_PASSWORD }}

on:
  workflow_dispatch:
    inputs:
      rc_version:
        description: 'Beta release name. e.g 7.6.0-beta01'
        required: true

permissions:
  contents: write

jobs:
  release:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Decode Keystore
        run: |
          mkdir "$RUNNER_TEMP"/keystore
          echo $mavenSigningKeyRingFileEncoded | base64 -di > "$RUNNER_TEMP"/keystore/2DE631C1.gpg
          echo "mavenSigningKeyRingFile=$RUNNER_TEMP/keystore/2DE631C1.gpg" >> $GITHUB_ENV

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Publish and close Sonatype repository
        run: |
          ./gradlew -Pversion=${{ inputs.rc_version }} publishReleasePublicationToQaRepository -x embrace-gradle-plugin-integration-tests:publishReleasePublicationToQaRepository -Dorg.gradle.parallel=false --no-build-cache --no-configuration-cache --stacktrace
