name: "Close Stale PRs"

on:
  workflow_dispatch:
  schedule:
    - cron: "30 1 * * *"

env:
  days-before-pr-stale: 20
  days-before-pr-close: 10
  operations-per-run: 100

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          exempt-pr-labels: "dependencies"
          stale-issue-label: "stale"
          stale-pr-label: "stale"
          stale-pr-message: "This PR is stale because it has been open ${{ env.days-before-pr-stale }} days with no activity. Remove stale label or comment or this PR will be closed in ${{ env.days-before-pr-close }} days."
          close-pr-message: "This PR was closed due to inactivity."
          days-before-pr-stale: ${{ env.days-before-pr-stale }}
          days-before-pr-close: ${{ env.days-before-pr-close }}
          operations-per-run: ${{ env.operations-per-run }}
