package io.embrace.android.embracesdk.semconv

/**
 * Autogenerated Embrace semantic conventions for 'emb.aei'.
 *
 * Embrace Application Exit Info attributes
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object EmbAeiAttributes {

    /**
     * The session ID associated with the AEI event.
     */
    @ExperimentalSemconv
    const val AEI_SESSION_ID: String = "aei_session_id"

    /**
     * The session part ID where the AEI occurred.
     */
    @ExperimentalSemconv
    const val AEI_SESSION_PART_ID: String = "aei_session_part_id"

    /**
     * The user session ID where the AEI occurred.
     */
    @ExperimentalSemconv
    const val AEI_USER_SESSION_ID: String = "aei_user_session_id"

    /**
     * A description of the application exit.
     */
    @ExperimentalSemconv
    const val DESCRIPTION: String = "description"

    /**
     * The exit status code of the process.
     */
    @ExperimentalSemconv
    const val EXIT_STATUS: String = "exit_status"

    /**
     * The importance level of the process at exit.
     */
    @ExperimentalSemconv
    const val PROCESS_IMPORTANCE: String = "process_importance"

    /**
     * Proportional set size of the process at exit (bytes).
     */
    @ExperimentalSemconv
    const val PSS: String = "pss"

    /**
     * The reason for the application exit.
     */
    @ExperimentalSemconv
    const val REASON: String = "reason"

    /**
     * Resident set size of the process at exit (bytes).
     */
    @ExperimentalSemconv
    const val RSS: String = "rss"

    /**
     * Error message if the session ID could not be determined.
     */
    @ExperimentalSemconv
    const val SESSION_ID_ERROR: String = "session_id_error"

    /**
     * The timestamp of the application exit event.
     */
    @ExperimentalSemconv
    const val TIMESTAMP: String = "timestamp"

    /**
     * The trace status at the time of exit.
     */
    @ExperimentalSemconv
    const val TRACE_STATUS: String = "trace_status"
}