package io.embrace.android.embracesdk.semconv

/**
 * Autogenerated Embrace semantic conventions for 'emb.anr'.
 *
 * Embrace ANR / thread blockage attributes
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object EmbAnrAttributes {

    /**
     * The number of stack frames in the thread sample.
     */
    @ExperimentalSemconv
    const val FRAME_COUNT: String = "frame_count"

    /**
     * The ANR interval code.
     */
    @ExperimentalSemconv
    const val INTERVAL_CODE: String = "interval_code"

    /**
     * The last known time the thread was responsive (nanoseconds since epoch).
     */
    @ExperimentalSemconv
    const val LAST_KNOWN_TIME_UNIX_NANO: String = "last_known_time_unix_nano"

    /**
     * The ANR sample code.
     */
    @ExperimentalSemconv
    const val SAMPLE_CODE: String = "sample_code"

    /**
     * The overhead of collecting this sample (nanoseconds).
     */
    @ExperimentalSemconv
    const val SAMPLE_OVERHEAD: String = "sample_overhead"

    /**
     * The priority of the blocked thread.
     */
    @ExperimentalSemconv
    const val THREAD_PRIORITY: String = "thread_priority"
}