package io.embrace.android.embracesdk.semconv

/**
 * Autogenerated Embrace semantic conventions for 'emb.app'.
 *
 * Embrace application-level attributes
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object EmbAppAttributes {

    /**
     * The number of times the SDK has begun startup since the app updated to the current app version, whether or not startup completed. Resets to 1 on the first SDK startup after the app version changes.
     */
    @ExperimentalSemconv
    const val EMB_APP_VERSION_STARTUP_COUNTER: String = "emb.app.version_startup_counter"
}