package io.embrace.android.embracesdk.semconv

/**
 * Autogenerated Embrace semantic conventions for 'emb.attachment'.
 *
 * Embrace log message attachment attributes
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object EmbAttachmentAttributes {

    /**
     * The error code associated with a failed log message attachment.
     */
    @ExperimentalSemconv
    const val EMB_ATTACHMENT_ERROR_CODE: String = "emb.attachment_error_code"

    /**
     * The ID of a user-hosted log message attachment.
     */
    @ExperimentalSemconv
    const val EMB_ATTACHMENT_ID: String = "emb.attachment_id"

    /**
     * The size of a log message attachment in bytes.
     */
    @ExperimentalSemconv
    const val EMB_ATTACHMENT_SIZE: String = "emb.attachment_size"

    /**
     * The URL of a user-hosted log message attachment.
     */
    @ExperimentalSemconv
    const val EMB_ATTACHMENT_URL: String = "emb.attachment_url"
}