package io.embrace.android.embracesdk.semconv

/**
 * Autogenerated Embrace semantic conventions for 'emb.android'.
 *
 * Embrace Android platform attributes
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object EmbAndroidAttributes {

    /**
     * Sequence number for the number of AEI crashes captured by Embrace on the device.
     */
    @ExperimentalSemconv
    const val EMB_ANDROID_AEI_CRASH_NUMBER: String = "emb.android.aei_crash_number"

    /**
     * Sequence number for the number of crashes captured by Embrace on the device.
     */
    @ExperimentalSemconv
    const val EMB_ANDROID_CRASH_NUMBER: String = "emb.android.crash_number"

    /**
     * A snapshot of the current call stack of the threads running in the app process.
     */
    @ExperimentalSemconv
    const val EMB_ANDROID_THREADS: String = "emb.android.threads"

    /**
     * The exception handling type - whether it's handled or unhandled.
     */
    @ExperimentalSemconv
    const val EMB_EXCEPTION_HANDLING: String = "emb.exception_handling"
}