package io.embrace.android.embracesdk.semconv

/**
 * Autogenerated Embrace semantic conventions for 'emb.app'.
 *
 * Embrace application-level attributes
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object EmbAppAttributes {

    /**
     * The number of times the app has started up for the current app version.
     */
    @ExperimentalSemconv
    const val EMB_APP_VERSION_STARTUP_COUNTER: String = "emb.app.version_startup_counter"
}