package io.embrace.android.embracesdk.semconv

/**
 * Autogenerated Embrace semantic conventions for 'emb.breadcrumb'.
 *
 * Embrace breadcrumb attributes
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object EmbBreadcrumbAttributes {

    /**
     * The breadcrumb message.
     */
    @ExperimentalSemconv
    const val MESSAGE: String = "message"
}