package io.embrace.android.embracesdk.semconv

/**
 * Autogenerated Embrace semantic conventions for 'emb.common'.
 *
 * Embrace attributes applicable to any telemetry
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object EmbCommonAttributes {

    /**
     * A blob that represents the state of all active experiments in which this app is participating in.
     */
    @ExperimentalSemconv
    const val EMB_EXPERIMENTS: String = "emb.experiments"

    /**
     * Set this to true when the telemetry is known to have been created through a manual instrumentation API call.
     */
    @ExperimentalSemconv
    const val EMB_MANUAL_INSTRUMENTATION: String = "emb.manual_instrumentation"
}