package io.embrace.android.embracesdk.semconv

/**
 * Autogenerated Embrace semantic conventions for 'emb.common'.
 *
 * Embrace attributes applicable to any telemetry
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object EmbCommonAttributes {

    /**
     * Set this to true when the telemetry is known to have been created through a manual instrumentation API call.
     */
    @ExperimentalSemconv
    const val EMB_MANUAL_INSTRUMENTATION: String = "emb.manual_instrumentation"
}