package io.embrace.android.embracesdk.semconv

/**
 * Autogenerated Embrace semantic conventions for 'emb.frame_counts'.
 *
 * Embrace dropped and expected frame counts over an interval, such as a foreground session part or a screen (experimental)
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object EmbFrameCountsAttributes {

    /**
     * Number of vsyncs in the interval that showed no new frame because a frame overran its deadline by more than the jank heuristic multiplier.
     */
    @ExperimentalSemconv
    const val SMOOTHNESS_DROPPED_FRAMES: String = "smoothness.dropped_frames"

    /**
     * Number of vsyncs in the interval: each rendered frame, plus the vsyncs its dropped frames spanned.
     */
    @ExperimentalSemconv
    const val SMOOTHNESS_EXPECTED_FRAMES: String = "smoothness.expected_frames"
}