package io.embrace.android.embracesdk.semconv

/**
 * Autogenerated Embrace semantic conventions for 'emb.memory_leak'.
 *
 * Embrace memory leak attributes (experimental)
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object EmbMemoryLeakAttributes {

    /**
     * The fully qualified class of the object that was not released.
     */
    @ExperimentalSemconv
    const val MEMORY_LEAK_CLASS_NAME: String = "memory_leak.class_name"

    /**
     * Milliseconds between the object's lifecycle ending and the leak being detected. The log is timestamped at the former, so this recovers the latter, and is also how long the object outlived its own lifecycle before anything noticed.
     */
    @ExperimentalSemconv
    const val MEMORY_LEAK_DETECTION_DELAY_MS: String = "memory_leak.detection_delay_ms"

    /**
     * The identity hash code of the object that was not released. With memory_leak.user_session_id and memory_leak.session_part_id it identifies one leaked instance, so that repeated reports of the same leak can be recognised as the same leak. Stable for the lifetime of the object, but a hash rather than a guaranteed-unique identifier, so treat a match as strong evidence rather than proof.
     */
    @ExperimentalSemconv
    const val MEMORY_LEAK_IDENTITY_HASH_CODE: String = "memory_leak.identity_hash_code"

    /**
     * The kind of object whose lifecycle ended without it being released. Supplied by whichever instrumentation tracked the object rather than fixed here, so that a module adding support for a new kind reports it without a schema change.
     */
    @ExperimentalSemconv
    const val MEMORY_LEAK_OBJECT_TYPE: String = "memory_leak.object_type"

    /**
     * The session part in which the object's lifecycle ended. Carried explicitly for the same reason as memory_leak.user_session_id, and likewise always populated.
     */
    @ExperimentalSemconv
    const val MEMORY_LEAK_SESSION_PART_ID: String = "memory_leak.session_part_id"

    /**
     * The user session in which the object's lifecycle ended. Carried explicitly because the leak is detected later than it is reported as having happened, so the session current at detection is not the one the leak belongs to. Always populated, as a leak whose session is unknown is not reported at all.
     */
    @ExperimentalSemconv
    const val MEMORY_LEAK_USER_SESSION_ID: String = "memory_leak.user_session_id"
}