package io.embrace.android.embracesdk.semconv

/**
 * Autogenerated Embrace semantic conventions for 'emb.network_request'.
 *
 * Embrace-specific network request attributes
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object EmbNetworkRequestAttributes {

    /**
     * Indicates the span should be forwarded to the customer's backend.
     */
    @ExperimentalSemconv
    const val EMB_FORWARD_TELEMETRY: String = "emb.forward_telemetry"

    /**
     * The Embrace trace ID used for correlation.
     */
    @ExperimentalSemconv
    const val EMB_TRACE_ID: String = "emb.trace_id"

    /**
     * The W3C traceparent header value forwarded with the network request.
     */
    @ExperimentalSemconv
    const val EMB_W3C_TRACEPARENT: String = "emb.w3c_traceparent"
}