package io.embrace.android.embracesdk.semconv

/**
 * Autogenerated Embrace semantic conventions for 'emb.network_state'.
 *
 * Embrace network connectivity state attributes
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object EmbNetworkStateAttributes {

    /**
     * The network connectivity status.
     */
    @ExperimentalSemconv
    const val NETWORK_STATUS: String = "network.status"

    object NetworkStatusValues {

        /**
         * No network reachability
         */
        @ExperimentalSemconv
        const val NOT_REACHABLE: String = "none"

        /**
         * Network present but not verified
         */
        @ExperimentalSemconv
        const val UNVERIFIED: String = "unverified"

        /**
         * WiFi connection
         */
        @ExperimentalSemconv
        const val WIFI: String = "wifi"

        /**
         * WiFi connection being established
         */
        @ExperimentalSemconv
        const val WIFI_CONNECTING: String = "wifi_connecting"

        /**
         * Mobile/WAN connection
         */
        @ExperimentalSemconv
        const val WAN: String = "wan"

        /**
         * Mobile/WAN connection being established
         */
        @ExperimentalSemconv
        const val WAN_CONNECTING: String = "wan_connecting"

        /**
         * Unknown network state
         */
        @ExperimentalSemconv
        const val UNKNOWN: String = "unknown"

        /**
         * Unknown network connection being established
         */
        @ExperimentalSemconv
        const val UNKNOWN_CONNECTING: String = "unknown_connecting"
    }
}