package io.embrace.android.embracesdk.semconv

/**
 * Autogenerated Embrace semantic conventions for 'emb.network_status'.
 *
 * Embrace network status attributes
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object EmbNetworkStatusAttributes {

    /**
     * The network connectivity status.
     */
    @ExperimentalSemconv
    const val NETWORK: String = "network"
}