package io.embrace.android.embracesdk.semconv

/**
 * Autogenerated Embrace semantic conventions for 'emb.network_captured_request'.
 *
 * Embrace network captured request attributes
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object EmbNetworkCapturedRequestAttributes {

    /**
     * The duration of the network request in milliseconds.
     */
    @ExperimentalSemconv
    const val DURATION: String = "duration"

    /**
     * The encrypted payload of the network request or response.
     */
    @ExperimentalSemconv
    const val ENCRYPTED_PAYLOAD: String = "encrypted-payload"

    /**
     * The end time of the network request in milliseconds since epoch.
     */
    @ExperimentalSemconv
    const val END_TIME: String = "end-time"

    /**
     * The ID of the network interface used for the request.
     */
    @ExperimentalSemconv
    const val NETWORK_ID: String = "network-id"

    /**
     * The body of the network request.
     */
    @ExperimentalSemconv
    const val REQUEST_BODY: String = "request-body"

    /**
     * The query parameters of the network request.
     */
    @ExperimentalSemconv
    const val REQUEST_QUERY: String = "request-query"

    /**
     * The size of the network request body in bytes.
     */
    @ExperimentalSemconv
    const val REQUEST_SIZE: String = "request-size"

    /**
     * The body of the network response.
     */
    @ExperimentalSemconv
    const val RESPONSE_BODY: String = "response-body"

    /**
     * The size of the network response body in bytes.
     */
    @ExperimentalSemconv
    const val RESPONSE_SIZE: String = "response-size"

    /**
     * The start time of the network request in milliseconds since epoch.
     */
    @ExperimentalSemconv
    const val START_TIME: String = "start-time"

    /**
     * The URL of the network request.
     */
    @ExperimentalSemconv
    const val URL: String = "url"
}