package io.embrace.android.embracesdk.semconv

/**
 * Autogenerated Embrace semantic conventions for 'emb.push_notification'.
 *
 * Embrace push notification attributes
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object EmbPushNotificationAttributes {

    /**
     * The body text of the push notification.
     */
    @ExperimentalSemconv
    const val NOTIFICATION_BODY: String = "notification.body"

    /**
     * The sender of the push notification.
     */
    @ExperimentalSemconv
    const val NOTIFICATION_FROM: String = "notification.from"

    /**
     * The ID of the push notification.
     */
    @ExperimentalSemconv
    const val NOTIFICATION_ID: String = "notification.id"

    /**
     * The priority of the push notification.
     */
    @ExperimentalSemconv
    const val NOTIFICATION_PRIORITY: String = "notification.priority"

    /**
     * The title of the push notification.
     */
    @ExperimentalSemconv
    const val NOTIFICATION_TITLE: String = "notification.title"

    /**
     * The type of push notification.
     */
    @ExperimentalSemconv
    const val NOTIFICATION_TYPE: String = "notification.type"
}