package io.embrace.android.embracesdk.semconv

/**
 * Autogenerated Embrace semantic conventions for 'emb.power_state'.
 *
 * Embrace device power state attributes
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object EmbPowerStateAttributes {

    /**
     * The device power mode.
     */
    @ExperimentalSemconv
    const val POWER_MODE: String = "power.mode"

    object PowerModeValues {

        /**
         * Normal power mode
         */
        @ExperimentalSemconv
        const val NORMAL: String = "normal"

        /**
         * Low power / battery saver mode
         */
        @ExperimentalSemconv
        const val LOW: String = "low"

        /**
         * Unknown power mode
         */
        @ExperimentalSemconv
        const val UNKNOWN: String = "unknown"
    }
}