package io.embrace.android.embracesdk.semconv

/**
 * Autogenerated Embrace semantic conventions for 'emb.responsiveness'.
 *
 * Embrace responsiveness vital attributes (experimental)
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object EmbResponsivenessAttributes {

    /**
     * How long it took from the raw touch event until the next frame was drawn in response, in milliseconds.
     */
    @ExperimentalSemconv
    const val RESPONSIVENESS_TAP_TO_FRAME_MS: String = "responsiveness.tap_to_frame_ms"

    /**
     * How long it took from that frame drawing until the main thread's queue next drained, in milliseconds.
     */
    @ExperimentalSemconv
    const val RESPONSIVENESS_FRAME_TO_DRAIN_MS: String = "responsiveness.frame_to_drain_ms"
}
