package io.embrace.android.embracesdk.semconv

/**
 * Autogenerated Embrace semantic conventions for 'emb.span'.
 *
 * Embrace span-level attributes
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object EmbSpanAttributes {

    /**
     * Error code indicating the reason a span ended unsuccessfully.
     */
    @ExperimentalSemconv
    const val EMB_ERROR_CODE: String = "emb.error_code"

    /**
     * Semantic meaning of a span link, defining the relationship between the containing span and the linked span.
     */
    @ExperimentalSemconv
    const val EMB_LINK_TYPE: String = "emb.link_type"

    /**
     * Denotes a private span recorded by Embrace for diagnostic or internal usage purposes.
     */
    @ExperimentalSemconv
    const val EMB_PRIVATE: String = "emb.private"

    /**
     * The reason an app instance terminated.
     */
    @ExperimentalSemconv
    const val EMB_TERMINATION_CAUSE: String = "emb.termination_cause"
}