package io.embrace.android.embracesdk.semconv

/**
 * Autogenerated Embrace semantic conventions for 'emb.session'.
 *
 * Embrace session attributes
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object EmbSessionAttributes {

    /**
     * Set to 1 if this session part is the known final part (max duration reached or manual termination). Omitted otherwise.
     */
    @ExperimentalSemconv
    const val EMB_IS_FINAL_SESSION: String = "emb.is_final_session"

    /**
     * UUID identifying the session.
     */
    @ExperimentalSemconv
    const val EMB_USER_SESSION_ID: String = "emb.user_session_id"

    /**
     * Incremental counter of sessions since SDK install.
     */
    @ExperimentalSemconv
    const val EMB_USER_SESSION_NUMBER: String = "emb.user_session_number"

    /**
     * Session start timestamp (milliseconds since epoch).
     */
    @ExperimentalSemconv
    const val EMB_USER_SESSION_START_TS: String = "emb.user_session_start_ts"
}