package io.embrace.android.embracesdk.semconv

/**
 * Autogenerated Embrace semantic conventions for 'emb.session'.
 *
 * Embrace session span attributes
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object EmbSessionAttributes {

    /**
     * Whether the session was ended by the SDK or an unexpected termination.
     */
    @ExperimentalSemconv
    const val EMB_CLEAN_EXIT: String = "emb.clean_exit"

    /**
     * Whether the session is a cold start.
     */
    @ExperimentalSemconv
    const val EMB_COLD_START: String = "emb.cold_start"

    /**
     * The crash report ID tied to the session.
     */
    @ExperimentalSemconv
    const val EMB_CRASH_ID: String = "emb.crash_id"

    /**
     * The number of free bytes on disk.
     */
    @ExperimentalSemconv
    const val EMB_DISK_FREE_BYTES: String = "emb.disk_free_bytes"

    /**
     * The number of error logs in a session.
     */
    @ExperimentalSemconv
    const val EMB_ERROR_LOG_COUNT: String = "emb.error_log_count"

    /**
     * Last known time that the session existed (nanoseconds since epoch).
     */
    @ExperimentalSemconv
    const val EMB_HEARTBEAT_TIME_UNIX_NANO: String = "emb.heartbeat_time_unix_nano"

    /**
     * Set to 1 if this session part is the known final part (max duration reached or manual termination). Omitted otherwise.
     */
    @ExperimentalSemconv
    const val EMB_IS_FINAL_SESSION: String = "emb.is_final_session"

    /**
     * Set to 1 when the SDK knows for certain this is the final part of a session (max duration reached, inactivity timeout, or manual termination). Omitted when the value would be 0.
     */
    @ExperimentalSemconv
    const val EMB_IS_FINAL_SESSION_PART: String = "emb.is_final_session_part"

    /**
     * How a signal should be delivered to the Embrace backend.
     */
    @ExperimentalSemconv
    const val EMB_PRIVATE_SEND_MODE: String = "emb.private.send_mode"

    /**
     * Unique ID assigned to each app instance.
     */
    @ExperimentalSemconv
    const val EMB_PRIVATE_SEQUENCE_ID: String = "emb.private.sequence_id"

    /**
     * Monotonically increasing sequence ID given to completed spans expected to be sent to the server.
     */
    @ExperimentalSemconv
    const val EMB_PROCESS_IDENTIFIER: String = "emb.process_identifier"

    /**
     * The session end type.
     */
    @ExperimentalSemconv
    const val EMB_SESSION_END_TYPE: String = "emb.session_end_type"

    /**
     * Session number (integer sequence ID).
     */
    @ExperimentalSemconv
    const val EMB_SESSION_NUMBER: String = "emb.session_number"

    /**
     * UUID identifying the session part.
     */
    @ExperimentalSemconv
    const val EMB_SESSION_PART_ID: String = "emb.session_part_id"

    /**
     * The session start type.
     */
    @ExperimentalSemconv
    const val EMB_SESSION_START_TYPE: String = "emb.session_start_type"

    /**
     * The name of the Activity that app startup completed in.
     */
    @ExperimentalSemconv
    const val EMB_STARTUP_ACTIVITY: String = "emb.startup_activity"

    /**
     * The startup duration in nanoseconds.
     */
    @ExperimentalSemconv
    const val EMB_STARTUP_DURATION: String = "emb.startup_duration"

    /**
     * The application state (foreground/background) at the time the log was recorded.
     */
    @ExperimentalSemconv
    const val EMB_STATE: String = "emb.state"

    /**
     * Whether the session was terminated.
     */
    @ExperimentalSemconv
    const val EMB_TERMINATED: String = "emb.terminated"

    /**
     * The reason the session part was terminated.
     */
    @ExperimentalSemconv
    const val EMB_TERMINATION_REASON: String = "emb.termination_reason"

    object EmbTerminationReasonValues {

        /**
         * Session ended because the maximum session duration was reached.
         */
        @ExperimentalSemconv
        const val MAX_DURATION_REACHED: String = "max_duration_reached"

        /**
         * Session ended due to inactivity timeout.
         */
        @ExperimentalSemconv
        const val INACTIVITY: String = "inactivity"

        /**
         * Session ended by manual termination.
         */
        @ExperimentalSemconv
        const val MANUAL: String = "manual"
    }

    /**
     * UUID identifying the session.
     */
    @ExperimentalSemconv
    const val EMB_USER_SESSION_ID: String = "emb.user_session_id"

    /**
     * The inactivity timeout (in minutes) that the SDK was configured to use.
     */
    @ExperimentalSemconv
    const val EMB_USER_SESSION_INACTIVITY_TIMEOUT_MINUTES: String = "emb.user_session_inactivity_timeout_minutes"

    /**
     * The maximum session duration (in minutes) that the SDK was configured to use.
     */
    @ExperimentalSemconv
    const val EMB_USER_SESSION_MAX_DURATION_MINUTES: String = "emb.user_session_max_duration_minutes"

    /**
     * Incremental counter of sessions since SDK install.
     */
    @ExperimentalSemconv
    const val EMB_USER_SESSION_NUMBER: String = "emb.user_session_number"

    /**
     * The index of the part within the session. 1-indexed, matching the behavior of session_number.
     */
    @ExperimentalSemconv
    const val EMB_USER_SESSION_PART_NUMBER: String = "emb.user_session_part_number"

    /**
     * Session start timestamp (milliseconds since epoch).
     */
    @ExperimentalSemconv
    const val EMB_USER_SESSION_START_TS: String = "emb.user_session_start_ts"
}
