package io.embrace.android.embracesdk.semconv

/**
 * Autogenerated Embrace semantic conventions for 'emb.state_transition'.
 *
 * Embrace state transition tracking attributes
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object EmbStateTransitionAttributes {

    /**
     * The number of transitions dropped by the instrumentation.
     */
    @ExperimentalSemconv
    const val EMB_STATE_DROPPED_BY_INSTRUMENTATION: String = "emb.state.dropped_by_instrumentation"

    /**
     * The initial value a state began with.
     */
    @ExperimentalSemconv
    const val EMB_STATE_INITIAL_VALUE: String = "emb.state.initial_value"

    /**
     * The value a state transitioned into in the given event.
     */
    @ExperimentalSemconv
    const val EMB_STATE_NEW_VALUE: String = "emb.state.new_value"

    /**
     * The number of transitions dropped because they didn't occur during a session.
     */
    @ExperimentalSemconv
    const val EMB_STATE_NOT_IN_SESSION: String = "emb.state.not_in_session"

    /**
     * The total number of transitions recorded explicitly in the given state span.
     */
    @ExperimentalSemconv
    const val EMB_STATE_TRANSITION_COUNT: String = "emb.state.transition_count"

    /**
     * The type of the state value recorded alongside it, i.e. of the initial value on a state span or of the new value on a transition event, recorded only when it is not the default type. The uniqueness of a state's value is defined by the pair of value and type.
     */
    @ExperimentalSemconv
    const val EMB_STATE_VALUE_TYPE: String = "emb.state.value_type"

    object EmbStateValueTypeValues {

        /**
         * A value generated by the SDK itself rather than observed from the app
         */
        @ExperimentalSemconv
        const val SYSTEM: String = "system"
    }
}