package io.embrace.android.embracesdk.semconv

/**
 * Autogenerated Embrace semantic conventions for 'emb.screen_load'.
 *
 * Embrace screen-load vital attributes (experimental)
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object EmbScreenLoadAttributes {

    /**
     * Duration from the navigation end event until the first frame rendered on the destination, in milliseconds.
     */
    @ExperimentalSemconv
    const val SCREEN_LOAD_FIRST_FRAME_DURATION_MS: String = "screen_load.first_frame_duration_ms"

    /**
     * Duration from the navigation start event until the navigation end event, in milliseconds.
     */
    @ExperimentalSemconv
    const val SCREEN_LOAD_NAV_DURATION_MS: String = "screen_load.nav_duration_ms"

    /**
     * Duration from the initial interaction until the navigation start event, in milliseconds.
     */
    @ExperimentalSemconv
    const val SCREEN_LOAD_NAV_START_DELAY_MS: String = "screen_load.nav_start_delay_ms"

    /**
     * How the screen load ended.
     */
    @ExperimentalSemconv
    const val SCREEN_LOAD_OUTCOME: String = "screen_load.outcome"
}