package io.embrace.android.embracesdk.semconv

/**
 * Autogenerated Embrace semantic conventions for 'emb.smoothness'.
 *
 * Embrace smoothness vital attributes (experimental)
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object EmbSmoothnessAttributes {

    /**
     * Number of frames rendered during the focal moment.
     */
    @ExperimentalSemconv
    const val SMOOTHNESS_FRAME_COUNT: String = "smoothness.frame_count"

    /**
     * Total jank over the focal moment, expressed in 60fps-reference frames.
     */
    @ExperimentalSemconv
    const val SMOOTHNESS_NORMALIZED_DROPPED_FRAMES: String = "smoothness.normalized_dropped_frames"

    /**
     * How the focal moment ended.
     */
    @ExperimentalSemconv
    const val SMOOTHNESS_OUTCOME: String = "smoothness.outcome"
}