package io.embrace.android.embracesdk.semconv

/**
 * Autogenerated Embrace semantic conventions for 'emb.telemetry'.
 *
 * Embrace SDK self-telemetry and environment attributes
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object EmbTelemetryAttributes {

    /**
     * Whether the app is running on an emulator.
     */
    @ExperimentalSemconv
    const val EMB_IS_EMULATOR: String = "emb.is_emulator"

    /**
     * The version of Kotlin found on the classpath.
     */
    @ExperimentalSemconv
    const val EMB_KOTLIN_ON_CLASSPATH: String = "emb.kotlin_on_classpath"

    /**
     * Whether OkHttp3 is present on the classpath.
     */
    @ExperimentalSemconv
    const val EMB_OKHTTP3: String = "emb.okhttp3"

    /**
     * The version of OkHttp3 found on the classpath.
     */
    @ExperimentalSemconv
    const val EMB_OKHTTP3_ON_CLASSPATH: String = "emb.okhttp3_on_classpath"

    /**
     * Storage available on the device in bytes.
     */
    @ExperimentalSemconv
    const val EMB_STORAGE_AVAILABLE: String = "emb.storage.available"

    /**
     * Storage used by Embrace in bytes.
     */
    @ExperimentalSemconv
    const val EMB_STORAGE_USED: String = "emb.storage.used"
}