package io.embrace.android.embracesdk.semconv

/**
 * Autogenerated Embrace semantic conventions for 'emb.thermal_state'.
 *
 * Embrace thermal state attributes
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object EmbThermalStateAttributes {

    /**
     * The thermal state status of the device.
     */
    @ExperimentalSemconv
    const val STATUS: String = "status"
}