package io.embrace.android.embracesdk.semconv

/**
 * Autogenerated Embrace semantic conventions for 'emb.tap'.
 *
 * Embrace tap breadcrumb attributes
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object EmbTapAttributes {

    /**
     * The coordinates of the tap event in x,y format.
     */
    @ExperimentalSemconv
    const val TAP_COORDS: String = "tap.coords"

    /**
     * The type of tap event (tap or long_press).
     */
    @ExperimentalSemconv
    const val TAP_TYPE: String = "tap.type"
}