package io.embrace.android.embracesdk.semconv

/**
 * Autogenerated Embrace semantic conventions for 'emb.tap'.
 *
 * Embrace tap breadcrumb attributes
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object EmbTapAttributes {

    /**
     * The name of the view/element that the tap event occurred in.
     */
    const val VIEW_NAME: String = "view.name"

    /**
     * The type of tap event (tap or long_press).
     */
    const val TAP_TYPE: String = "tap.type"

    /**
     * The coordinates of the tap event in x,y format.
     */
    const val TAP_COORDS: String = "tap.coords"
}
