package io.embrace.android.embracesdk.semconv

/**
 * Autogenerated Embrace semantic conventions for 'emb.view'.
 *
 * Embrace view/screen attributes
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object EmbViewAttributes {

    /**
     * The name of the view or screen.
     */
    @ExperimentalSemconv
    const val VIEW_NAME: String = "view.name"
}